//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8000.
// 
namespace SmartDeviceProject1.ZSDI506 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“Policy”。
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="binding", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZSDI506 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ZSDI506() {
            this.Url = "http://sapdev.orgcanmaking.com:8000/sap/bc/srt/rfc/sap/zsdi506/500/zsdi506/bindin" +
                "g";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Zsdi506Response", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public Zsdi506Response Zsdi506([System.Xml.Serialization.XmlElementAttribute("Zsdi506", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] Zsdi506 Zsdi5061) {
            object[] results = this.Invoke("Zsdi506", new object[] {
                        Zsdi5061});
            return ((Zsdi506Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginZsdi506(Zsdi506 Zsdi5061, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Zsdi506", new object[] {
                        Zsdi5061}, callback, asyncState);
        }
        
        /// <remarks/>
        public Zsdi506Response EndZsdi506(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Zsdi506Response)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsdi506 {
        
        private string vbelnField;
        
        private string z1Field;
        
        private string z2Field;
        
        private string z3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vbeln {
            get {
                return this.vbelnField;
            }
            set {
                this.vbelnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Z1 {
            get {
                return this.z1Field;
            }
            set {
                this.z1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Z2 {
            get {
                return this.z2Field;
            }
            set {
                this.z2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Z3 {
            get {
                return this.z3Field;
            }
            set {
                this.z3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsdi506Response {
    }
}
